#!/bin/bash
cd "$(dirname "$0")"

set -e

if [[ $# -ne 1 ]] ; then
    echo Usage:
    echo   create-initial-cert [DRONE_HOST]
    echo Example:
    echo   create-initial-cert example.com
    exit 0
fi

DRONE_HOST=$1

echo Obtaining brand-new letsencrypt certs and generating strong Diffie-Hellman parameters

docker-compose build

docker-compose run --rm \
    -p 80:80 \
    -p 443:443 \
    -e DRONE_HOST=$DRONE_HOST \
    certbot

echo Done generating certs and keys
